### ISSUE TITLE
Frontend manual

### ISSUE THREAD

**Issue by shinokada** [AsgardCms/Documentation#12]
Hi,

Thank you for your hard work.
Is there any documentation about how to get started front-end?

**Comment by nWidart** [comment]
Hi,

Yes, on the documentation: https://asgardcms.com/docs/v1/themes/usage

Also the screencast: https://www.youtube.com/watch?v=7AbUJVWj1sI

**Comment by shinokada** [comment]
Thanks.
BTW
How can I control Page template name in pages/create ? How to add templates?

I read the document on Page, but I couldn't find any info.

![image](https://cloud.githubusercontent.com/assets/147320/17051272/1cbb03ae-4ff8-11e6-825b-5d0e4b73e7e5.png)

**Comment by nWidart** [comment]
This is not the medium for those questions. Please ask on the forum or on Slack.
