### ISSUE TITLE
Install/update module page

### ISSUE THREAD

**Issue by Grummfy** [AsgardCms/Documentation#5]
Can you create a page explaining how to install/update a module:
- composer require
- database migration

This page can be referenced on all readme module.

Thanks.

**Comment by nWidart** [comment]
I'm trying to think of a good place to put this information, under which title, which page. Putting this in its own dedicated page might feel a little empty, since there'll only be that info.

**Comment by nWidart** [comment]
Added the required information in the installation page.

https://asgardcms.com/en/docs/getting-started/installation

**Comment by Grummfy** [comment]
thanks
